name: first workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello GitHub Actions
        run: echo "This is first my workflow"

      - name: Bye GitHub Actions
        run: echo "Bye workflow"
