name: second workflow
on: workflow_dispatch
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hy my second workflow
        run: echo " this is my second workflow"

  my-job2:
     runs-on: ubuntu-latest
     steps:
         - name: "crate my second job"
           run: echo "Crate a new job"
