name: Validate Files

on:
  push:

jobs:
  validate-file:
    runs-on: ubuntu-latest

    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Validate HTML file
        run: test -f index.html

      - name: Validate JS code
        run: node --check script.js